 DROP TABLE SAMPLE_T;
 DROP SEQUENCE SAMPLE_SEQ;
 
 CREATE TABLE SAMPLE_T(
  SAMPLE_NO      NUMBER NOT NULL,
  SAMPLE_CONTENT VARCHAR2(100 BYTE),
  SAMPLE_EDITOR  VARCHAR2(100 BYTE),
  SAMPLE_DT      DATE,
  CONSTRAINT PK_SAMPLE PRIMARY KEY(SAMPLE_NO)
  );
  
  CREATE SEQUENCE SAMPLE_SEQ NOCACHE;
  
 